controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

inici:
    path: /
    controller: App\Controller\IniciController::inici

logout:
    path: /logout